### ISSUE TITLE
Odd and Even number evaluation does not work

### ISSUE THREAD

**Issue by ama1998** [mmbc2008/CreditCard#10]

**Comment by mmbc2008** [comment]
@ama1998 I have fixed the most recent issue to do with the list conversion. However, it seems that the methods that you wrote for the odd and even rules do not multiply or add up any numbers from each list. We need to discuss this in the group meeting tomorrow.

**Comment by ama1998** [comment]
Ok, that will do! until then.

**Comment by mmbc2008** [comment]
We're fixing this by using the blueprint of @bosduco basic code
